name: testing-pipeline
on:
  workflow_run:
    workflows:
      - create-pipeline
    types:
      - completed
jobs:
  preprocessing-and-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install CDK modules
        working-directory: Credibility-Assessment-Framework/Credibility-Development-Kit
        run: find . -maxdepth 4 -name package.json -exec sh -c 'for file do dir=${file%/*}; npm install --prefix $dir $dir; done' sh {} +