name: continuous-dynamic-simulation-testing
on: push

jobs:
  run-simulation:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout simulation data
        uses: actions/checkout@v4
        with: 
          path: 'simdata'
      - name: integrate SSV in SSD
        # generating 2 files, for testing the run-openmcx
        working-directory: simdata/util/ssv_ssd_integrator
        run: |
          ./install_prerequisites.sh
          mkdir ../../systems/variations
          node ./ssv_to_ssd_inline.js -i ../../systems/ssd/dc_motor_system.ssd -o ../../systems/variations/dc_motor_system_1.ssd
          node ./ssv_to_ssd_inline.js -i ../../systems/ssd/dc_motor_system.ssd -o ../../systems/variations/dc_motor_system_2.ssd
      - name: run openmcx
        uses: localhorst87/run-openmcx@v0.3.0
        with: 
          ssd: ./simdata/systems/variations
          resultDir: ./simdata/results/
      - name: display results
        run: |
          cat ./simdata/results/dc_motor_system_1/mechanics_res.csv
          cat ./simdata/results/dc_motor_system_2/electrics_res.csv
