name: continuous-dynamic-simulation-testing
on: push

jobs:
  run-simulation:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout simulation data
        uses: actions/checkout@v4
        with: 
          path: 'simdata'
      - name: integrate SSV in SSD
        working-directory: simdata/util/ssv_ssd_integrator
        run: |
          ./install_prerequisites.sh
          node ./ssv_to_ssd_inline.js -i ../../systems/dc_motor_system.ssd -o ../../systems/dc_motor_system.ssd
          cat ../../systems/dc_motor_system.ssd
      - name: run openmcx
        uses: localhorst87/run-openmcx@v0.1
        with: 
          ssd: ./simdata/systems/dc_motor_system.ssd
      - name: display results
        run: cat ./results/mechanics_res.csv
                      
                  
                  
                    
                  
                
            
            
          
        
          
        
      
  
  
